version: '3'
services:
  my-app:
    build:
      context: .
      dockerfile: ./node.js_project/app/Dockerfile
    image: 885554903941.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0
    ports:
     - 3000:3000
    depends_on:
      - mongodb
      - mongo-express

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password1
    volumes:
      - mongo-data:/data/db
      
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password1
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
