name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Build Docker images
      - name: Build Docker images
        run: |
          docker compose -f docker-compose.yml build

      # 5️⃣ Run tests inside the container
      - name: Run tests
        run: |
          docker compose -f docker-compose.yml up -d db
          docker compose -f docker-compose.yml run --rm web bash -c "
            python -m unittest discover -s tests || exit 1
          "
          docker compose -f docker-compose.yml down

      # 6️⃣ Tag and push Docker image
      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/flask-postgres:latest
          docker tag my-flask-compose-app_web $IMAGE_NAME
          docker push $IMAGE_NAME
